version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
#            - PGDATA=/var/lib/postgresql/data/pgdata
#        volumes:
#            - ./mnt/postgres:/var/lib/postgresql/data/pgdata

    webserver:
        build:
            context: ./docker/airflow
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - PYTHONPATH=/usr/local/airflow/conf/
        volumes:
            - ./mnt/airflow/dags:/usr/local/airflow/dags
            - ./mnt/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./mnt/airflow/logs:/usr/local/airflow/logs
            - ./mnt/airflow/conf:/usr/local/airflow/conf
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
            context: ./docker/airflow
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
            context: ./docker/airflow
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./mnt/airflow/dags:/usr/local/airflow/dags
            - ./mnt/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./mnt/airflow/logs:/usr/local/airflow/logs   
            - ./mnt/airflow/conf:/usr/local/airflow/conf
        # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - PYTHONPATH=/usr/local/airflow/conf/
        command: scheduler

    worker:
        build:
            context: ./docker/airflow
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./mnt/airflow/dags:/usr/local/airflow/dags
            - ./mnt/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./mnt/airflow/logs:/usr/local/airflow/logs   
            - ./mnt/airflow/conf:/usr/local/airflow/conf  
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - PYTHONPATH=/usr/local/airflow/conf/
        command: worker

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        restart: always
        depends_on: 
            - worker
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            discovery.type: single-node
        ports: 
            - "9200:9200"
            - "9300:9300"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.2
        restart: always
        depends_on:
            - elasticsearch
        volumes: 
            - ./mnt/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        environment: 
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
            SERVER_HOST: "0.0.0.0"
        ports: 
            - "5601:5601"

    logstash:
        image: docker.elastic.co/logstash/logstash:7.5.2
        restart: always
        depends_on:
            - elasticsearch
        volumes:
            - ./mnt/logstash/pipeline:/usr/share/logstash/pipeline
    
    
