apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
