apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
 volumes:
  - name: nginx-conf
    configMap:
     name: nginx-cm
     items:
      - key: default.conf
        path: default.conf
 containers:
  - image: nginx
    name: nginx
    volumeMounts:
     - name: nginx-conf
       mountPath: /etc/nginx/conf.d/
