apiVersion: v1
kind: Pod
metadata:
 name: busybox
spec:
 containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: CHANNELNAME
      valueFrom:
       configMapKeyRef:
        name: demo-configmap
        key: channel.name
    - name: CHANNELOWNER
      valueFrom:
       configMapKeyRef:
        name: demo-configmap
        key: channel.owner
