apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-hostpath
spec:
 storageClassName: manual # Must match with the PV StorageClassName
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 100Mi
