apiVersion: v1
kind: LimitRange
metadata:
 name: mem-limitrange
 namespace: quota-demo-ns
spec:
 limits: # Avoid needing to specify quota limits for within each pod with limitrange
  - default:
     memory: 300Mi
    defaultRequest:
     memory: 50Mi
    type: Container
